Improve Dockerfile and workflows

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -18,6 +18,10 @@ jobs:
     name: Docker Build & Publish
     runs-on: ubuntu-latest
 
+    strategy:
+      matrix:
+        image: [ 'alpine' ]
+
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -63,17 +67,17 @@ jobs:
             exit 1
           fi
 
-          docker_file="Dockerfile"
-          base_image=$(grep 'FROM ' $docker_file | tail -1 | cut -f2 -d' ')
+          docker_file=".docker/${{matrix.image}}.docker"
+          base_image=$(grep 'FROM ' $docker_file | grep -v 'builder' | sed 's#${REGISTRY}/##' | tail -1 | cut -f2 -d' ')
 
           if [[ -z "$base_image" ]] ; then
             echo "::error::Can't extract base image info"
             exit 1
           fi
 
-          echo "::set-output name=version::$version"
-          echo "::set-output name=dockerfile::$docker_file"
-          echo "::set-output name=baseimage::$base_image"
+          echo "version=$version" >> $GITHUB_OUTPUT
+          echo "dockerfile=$docker_file" >> $GITHUB_OUTPUT
+          echo "baseimage=$base_image" >> $GITHUB_OUTPUT
 
           echo -e "\033[34mVersion:\033[0m    $version"
           echo -e "\033[34mDockerfile:\033[0m $docker_file"
@@ -83,14 +87,14 @@ jobs:
         id: build_check
         run: |
           if [[ "${{github.event_name}}" == "release" ]] ; then
-            echo "::set-output name=build::true"
+            echo "build=true" >> $GITHUB_OUTPUT
             exit 0
           fi
 
           echo -e "::group::\033[34mDownloading built image…\033[0m"
 
-          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:latest ; then
-            echo "::error::Can't download image ghcr.io/${{env.IMAGE_NAME}}:latest"
+          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}} ; then
+            echo "::error::Can't download image ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}"
             exit 1
           fi
 
@@ -111,27 +115,40 @@ jobs:
             exit 1
           fi
 
-          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:latest" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
+          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
             echo "::warning::Rebuild image (reason: base image rebuilt)"
-            echo "::set-output name=build::true"
+            echo "build=true" >> $GITHUB_OUTPUT
             exit 0
           fi
 
-      - name: Build and push Docker image
+      - name: Build and push Docker images (Docker)
         if: ${{ steps.build_check.outputs.build == 'true' }}
         uses: docker/build-push-action@v3
         with:
           push: true
           context: .
           file: ${{steps.metadata.outputs.dockerfile}}
+          build-args: |
+            REGISTRY=docker.io
           tags: |
-            ghcr.io/${{env.IMAGE_NAME}}:${{steps.metadata.outputs.version}}
-            ghcr.io/${{env.IMAGE_NAME}}:latest
-            ${{env.IMAGE_NAME}}:${{steps.metadata.outputs.version}}
-            ${{env.IMAGE_NAME}}:latest
+            ${{env.IMAGE_NAME}}:${{matrix.image}}-${{steps.metadata.outputs.version}}
+            ${{env.IMAGE_NAME}}:${{matrix.image}}
+
+      - name: Build and push Docker images (GHCR)
+        if: ${{ steps.build_check.outputs.build == 'true' }}
+        uses: docker/build-push-action@v3
+        with:
+          push: true
+          context: .
+          file: ${{steps.metadata.outputs.dockerfile}}
+          build-args: |
+            REGISTRY=ghcr.io
+          tags: |
+            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}-${{steps.metadata.outputs.version}}
+            ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}
 
       - name: Show info about built Docker image
         uses: essentialkaos/docker-info-action@v1
         with:
-          image: ghcr.io/${{env.IMAGE_NAME}}:latest
+          image: ghcr.io/${{env.IMAGE_NAME}}:${{matrix.image}}
           show-labels: true
